---
- name: Delete Users
  hosts: all
  tasks:
    - name: Delete Users from RedHat Family
      when: ansible_os_family == "RedHat"
      user:
        name: "{{ item }}"
        state: absent
      with_items:
        - bob
        - ben
        - lola
        - lisa
        - bryan
        - oliver
